apiVersion: autoscaling.vhape.io/v1alpha1
kind: VhapeWatchedNamespaceRegex
metadata:
  name: production-namespaces # Name of this namespace matching rule.
spec:
  # Regular expression used to select namespaces.
  # This example matches namespaces starting with "prod-".
  regex: "^prod-.*$"
  vhapePolicyName: vhape-policy-p93-default # cluster-scoped VhapePolicy used by managed VPAs
  vpaUpdateMode: InPlaceOrRecreate # update mode used by managed VPAs
