apiVersion: autoscaling.vhape.io/v1alpha1
kind: VhapeWatchedNamespace
metadata:
  name: production # namespace to be managed by the VHAPE Watcher
spec:
  vhapePolicyName: p93-percentile-hysteresis # VhapePolicy used by watcher-managed VPAs in this namespace
  vpaUpdateMode: InPlaceOrRecreate # update mode used by watcher-managed VPAs in this namespace