apiVersion: autoscaling.vhape.io/v1alpha1
kind: VhapeIgnoredWorkload
metadata:
  name: legacy-api-deployment-production # name of the exclusion rule
spec:
  targetRef: # Deployment to be excluded from Watcher management
    apiVersion: apps/v1
    kind: Deployment
    namespace: production # namespace where the Deployment is defined
    name: legacy-api # name of the Deployment
  reason: "VPA managed manually" # optional reason for excluding the workload