apiVersion: apps/v1
kind: Deployment
metadata:
  name: vhape-recommender
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vhape-recommender
  template:
    metadata:
      labels:
        app: vhape-recommender
    spec:
      serviceAccountName: vhape-recommender
      containers:
        - name: vhape-recommender
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /recommender
          args:
            - --recommender-name=vhape-recommender
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          
          volumeMounts:
            - name: samples-warm-up-csv
              mountPath: /var/lib/vhape-recommender/samples-warm-up.csv

      volumes:
        - name: samples-warm-up-csv
          hostPath:
            path: /data/vhape-recommender/samples-warm-up.csv
            type: File