apiVersion: apps/v1
kind: Deployment
metadata:
  name: vhape-recommender
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vhape-recommender
  template:
    metadata:
      labels:
        app: vhape-recommender
      {{- if .Values.metrics.scrape }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: {{ .Values.metrics.port | quote }}
        prometheus.io/path: /metrics
      {{- end }}
    spec:
      serviceAccountName: vhape-recommender
      containers:
        - name: vhape-recommender
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /recommender
          args:
            - --recommender-name=vhape-recommender
            - --address=:{{ .Values.metrics.port }}
          ports:
            - name: metrics
              containerPort: {{ .Values.metrics.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}