apiVersion: autoscaling.vhape.io/v1alpha1
kind: VhapePolicy
metadata:
  name: p93-percentile-hysteresis
spec:
  resources:
    cpu:
      percentile-hysteresis:
        percentile: 0.93
        headroom: 0.10
        slidingWindow: 24h
        minimumCoverageWindow: 30m
    memory:
      percentile-hysteresis:
        percentile: 0.93
        headroom: 0.05
        slidingWindow: 24h
        minimumCoverageWindow: 30m
  scalingRule: ""
