{{- range .Values.policies }}
---
apiVersion: autoscaling.vhape.io/v1alpha1
kind: VhapePolicy
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
spec:
  resources:
    cpu:
{{ toYaml .cpu | indent 6 }}
    memory:
{{ toYaml .memory | indent 6 }}
  scalingRule: {{ .scalingRule | quote }}
{{ end }}