package watchers

import (
	"strings"

	appsv1 "k8s.io/api/apps/v1"
	vpav1 "k8s.io/autoscaler/vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1"
	vhapev1alpha1 "k8s.io/autoscaler/vertical-pod-autoscaler/pkg/apis/autoscaling.vhape.io/v1alpha1"
	"k8s.io/client-go/tools/cache"
	"k8s.io/klog/v2"
)

const (
	deploymentAPIVersion = "apps/v1"
	deploymentKind       = "Deployment"
)

// A new Deployment may require a generated VPA if its namespace is watched and
// the workload is not ignored.
func (w *Watchers) onDeploymentAdd(obj interface{}) {
	dep, ok := deploymentFromObject(obj)
	if !ok {
		klog.V(4).InfoS("Ignoring Deployment add event with unexpected object type")
		return
	}

	klog.V(4).InfoS("Enqueuing Deployment after add event", "deployment", klog.KObj(dep))
	w.sink.EnqueueDeployment(dep.Namespace, dep.Name)
}

// Deployment updates are ignored because Deployment spec changes do not affect
// the VPA object generated by the watcher.
func (w *Watchers) onDeploymentUpdate(_, _ interface{}) {
	klog.V(4).InfoS("Ignoring Deployment update event")
}

// Deployment deletes are ignored. If a Deployment is replaced with the same
// namespace/name and a new UID, the old generated VPA should be removed by
// Kubernetes garbage collection through ownerReferences. The VPA delete event
// will enqueue the Deployment again and the reconciler will create a new
// generated VPA if needed.
func (w *Watchers) onDeploymentDelete(_ interface{}) {
	klog.V(4).InfoS("Ignoring Deployment delete event")
}

// A new VPA may create a conflict with a generated VPA or with a watched Deployment.
func (w *Watchers) onVPAAdd(obj interface{}) {
	klog.V(4).InfoS("VPA add event")

	vpa, ok := vpaFromObject(obj)
	if !ok {
		klog.V(4).InfoS("Ignoring VPA add event with unexpected object type")
		return
	}

	w.enqueueDeploymentFromVPA(vpa, "vpa-add")
}

// A VPA update may change its targetRef. Enqueue both the old and the new target
// identities so the reconciler can evaluate the current desired state for each
// affected Deployment.
func (w *Watchers) onVPAUpdate(oldObj, newObj interface{}) {
	klog.V(4).InfoS("VPA update event")

	oldVPA, ok := vpaFromObject(oldObj)
	if ok {
		w.enqueueDeploymentFromVPA(oldVPA, "vpa-update-old")
	} else {
		klog.V(4).InfoS("Ignoring old object from VPA update event with unexpected object type")
	}

	newVPA, ok := vpaFromObject(newObj)
	if ok {
		w.enqueueDeploymentFromVPA(newVPA, "vpa-update-new")
	} else {
		klog.V(4).InfoS("Ignoring new object from VPA update event with unexpected object type")
	}
}

// If a VPA is deleted and the target Deployment is still in scope, the
// reconciler may recreate the generated VPA.
func (w *Watchers) onVPADelete(obj interface{}) {
	klog.V(4).InfoS("VPA deletion event")

	vpa, ok := vpaFromObject(obj)
	if !ok {
		klog.V(4).InfoS("Ignoring VPA delete event with unexpected object type")
		return
	}

	w.enqueueDeploymentFromVPA(vpa, "vpa-delete")
}

// When a namespace becomes watched, every Deployment in that namespace may need
// a generated VPA.
func (w *Watchers) onWatchedNamespaceAdd(obj interface{}) {
	watched, ok := watchedNamespaceFromObject(obj)
	if !ok {
		klog.V(4).InfoS("Ignoring VhapeWatchedNamespace add event with unexpected object type")
		return
	}

	klog.InfoS("Watched namespace added; enqueuing Deployments in namespace", "namespace", watched.Name)
	w.sink.EnqueueDeploymentsInNamespace(watched.Name)
}

// Watched namespace updates may change the assigned policy or the updatemode.
func (w *Watchers) onWatchedNamespaceUpdate(_, newObj interface{}) {
	klog.V(4).InfoS("VhapeWatchedNamespace update event")

	watched, ok := watchedNamespaceFromObject(newObj)
	if !ok {
		klog.V(4).InfoS("Ignoring VhapeWatchedNamespace update event with unexpected object type")
		return
	}

	klog.InfoS("Watched namespace updated; enqueuing Deployments in namespace", "namespace", watched.Name)
	w.sink.EnqueueDeploymentsInNamespace(watched.Name)
}

// When a namespace stops being watched, all Deployments in that namespace are
// reconciled so managed VPAs can be cleaned up.
func (w *Watchers) onWatchedNamespaceDelete(obj interface{}) {
	watched, ok := watchedNamespaceFromObject(obj)
	if !ok {
		klog.V(4).InfoS("Ignoring VhapeWatchedNamespace delete event with unexpected object type")
		return
	}

	klog.InfoS("Watched namespace deleted; enqueuing Deployments in namespace", "namespace", watched.Name)
	w.sink.EnqueueDeploymentsInNamespace(watched.Name)
}

// When a workload becomes ignored, the associated Deployment must be reconciled
// so any generated VPA can be cleaned up according to the watcher policy.
func (w *Watchers) onIgnoredWorkloadAdd(obj interface{}) {
	klog.V(4).InfoS("VhapeIgnoredWorkload add event")

	ignored, ok := ignoredWorkloadFromObject(obj)
	if !ok {
		klog.V(4).InfoS("Ignoring VhapeIgnoredWorkload add event with unexpected object type")
		return
	}

	w.enqueueDeploymentFromIgnoredWorkload(ignored)
}

// An ignored workload update may change its targetRef. Enqueue both the old and
// the new target identities so the reconciler can evaluate the current desired
// state for each affected Deployment.
func (w *Watchers) onIgnoredWorkloadUpdate(oldObj, newObj interface{}) {
	klog.V(4).InfoS("VhapeIgnoredWorkload update event")

	oldIgnored, ok := ignoredWorkloadFromObject(oldObj)
	if ok {
		w.enqueueDeploymentFromIgnoredWorkload(oldIgnored)
	} else {
		klog.V(4).InfoS("Ignoring old object from VhapeIgnoredWorkload update event with unexpected object type")
	}

	newIgnored, ok := ignoredWorkloadFromObject(newObj)
	if ok {
		w.enqueueDeploymentFromIgnoredWorkload(newIgnored)
	} else {
		klog.V(4).InfoS("Ignoring new object from VhapeIgnoredWorkload update event with unexpected object type")
	}
}

// When a workload stops being ignored, the target Deployment may need a generated
// VPA if it is still in a watched namespace.
func (w *Watchers) onIgnoredWorkloadDelete(obj interface{}) {
	klog.V(4).InfoS("VhapeIgnoredWorkload deletion event")

	ignored, ok := ignoredWorkloadFromObject(obj)
	if !ok {
		klog.V(4).InfoS("Ignoring VhapeIgnoredWorkload delete event with unexpected object type")
		return
	}

	w.enqueueDeploymentFromIgnoredWorkload(ignored)
}

func (w *Watchers) enqueueDeploymentFromVPA(vpa *vpav1.VerticalPodAutoscaler, reason string) {
	if vpa == nil {
		return
	}
	if vpa.Spec.TargetRef == nil {
		klog.V(4).InfoS("Ignoring VPA event without targetRef", "vpa", klog.KObj(vpa), "reason", reason)
		return
	}

	ref := vpa.Spec.TargetRef
	if !isDeploymentTarget(ref.APIVersion, ref.Kind, ref.Name) {
		klog.V(4).InfoS("Ignoring VPA event for non-Deployment target", "vpa", klog.KObj(vpa), "apiVersion", ref.APIVersion, "kind", ref.Kind, "name", ref.Name, "reason", reason)
		return
	}

	klog.V(4).InfoS("Enqueuing Deployment from VPA event", "deployment", klog.KRef(vpa.Namespace, ref.Name), "vpa", klog.KObj(vpa), "reason", reason)
	w.sink.EnqueueDeployment(vpa.Namespace, ref.Name)
}

func (w *Watchers) enqueueDeploymentFromIgnoredWorkload(ignored *vhapev1alpha1.VhapeIgnoredWorkload) {
	if ignored == nil {
		return
	}

	ref := ignored.Spec.TargetRef
	if !isDeploymentTarget(ref.APIVersion, ref.Kind, ref.Name) {
		klog.Warningf(
			"Ignoring VhapeIgnoredWorkload %q with unsupported or incomplete targetRef: apiVersion=%q kind=%q name=%q",
			ignored.Name,
			ref.APIVersion,
			ref.Kind,
			ref.Name,
		)
		return
	}
	if ref.Namespace == "" {
		klog.Warningf("Ignoring VhapeIgnoredWorkload %q with empty targetRef.namespace", ignored.Name)
		return
	}

	klog.V(4).InfoS(
		"Enqueuing Deployment from VhapeIgnoredWorkload event",
		"deployment", klog.KRef(ref.Namespace, ref.Name),
		"ignoredWorkload", klog.KObj(ignored),
		"ignoredReason", ignored.Spec.Reason,
	)
	w.sink.EnqueueDeployment(ref.Namespace, ref.Name)
}

func isDeploymentTarget(apiVersion, kind, name string) bool {
	return apiVersion == deploymentAPIVersion &&
		strings.EqualFold(kind, deploymentKind) &&
		name != ""
}

func deploymentFromObject(obj interface{}) (*appsv1.Deployment, bool) {
	dep, ok := obj.(*appsv1.Deployment)
	return dep, ok
}

func vpaFromObject(obj interface{}) (*vpav1.VerticalPodAutoscaler, bool) {
	if vpa, ok := obj.(*vpav1.VerticalPodAutoscaler); ok {
		return vpa, true
	}

	tombstone, ok := obj.(cache.DeletedFinalStateUnknown)
	if !ok {
		return nil, false
	}

	vpa, ok := tombstone.Obj.(*vpav1.VerticalPodAutoscaler)
	return vpa, ok
}

func watchedNamespaceFromObject(obj interface{}) (*vhapev1alpha1.VhapeWatchedNamespace, bool) {
	if watched, ok := obj.(*vhapev1alpha1.VhapeWatchedNamespace); ok {
		return watched, true
	}

	tombstone, ok := obj.(cache.DeletedFinalStateUnknown)
	if !ok {
		return nil, false
	}

	watched, ok := tombstone.Obj.(*vhapev1alpha1.VhapeWatchedNamespace)
	return watched, ok
}

func ignoredWorkloadFromObject(obj interface{}) (*vhapev1alpha1.VhapeIgnoredWorkload, bool) {
	if ignored, ok := obj.(*vhapev1alpha1.VhapeIgnoredWorkload); ok {
		return ignored, true
	}

	tombstone, ok := obj.(cache.DeletedFinalStateUnknown)
	if !ok {
		return nil, false
	}

	ignored, ok := tombstone.Obj.(*vhapev1alpha1.VhapeIgnoredWorkload)
	return ignored, ok
}
