//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in ResourceHeuristics) DeepCopyInto(out *ResourceHeuristics) {
	{
		in := &in
		*out = make(ResourceHeuristics, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
		return
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceHeuristics.
func (in ResourceHeuristics) DeepCopy() ResourceHeuristics {
	if in == nil {
		return nil
	}
	out := new(ResourceHeuristics)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VhapeIgnoredNamespace) DeepCopyInto(out *VhapeIgnoredNamespace) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VhapeIgnoredNamespace.
func (in *VhapeIgnoredNamespace) DeepCopy() *VhapeIgnoredNamespace {
	if in == nil {
		return nil
	}
	out := new(VhapeIgnoredNamespace)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VhapeIgnoredNamespace) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VhapeIgnoredNamespaceList) DeepCopyInto(out *VhapeIgnoredNamespaceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VhapeIgnoredNamespace, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VhapeIgnoredNamespaceList.
func (in *VhapeIgnoredNamespaceList) DeepCopy() *VhapeIgnoredNamespaceList {
	if in == nil {
		return nil
	}
	out := new(VhapeIgnoredNamespaceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VhapeIgnoredNamespaceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VhapeIgnoredWorkload) DeepCopyInto(out *VhapeIgnoredWorkload) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VhapeIgnoredWorkload.
func (in *VhapeIgnoredWorkload) DeepCopy() *VhapeIgnoredWorkload {
	if in == nil {
		return nil
	}
	out := new(VhapeIgnoredWorkload)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VhapeIgnoredWorkload) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VhapeIgnoredWorkloadList) DeepCopyInto(out *VhapeIgnoredWorkloadList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VhapeIgnoredWorkload, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VhapeIgnoredWorkloadList.
func (in *VhapeIgnoredWorkloadList) DeepCopy() *VhapeIgnoredWorkloadList {
	if in == nil {
		return nil
	}
	out := new(VhapeIgnoredWorkloadList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VhapeIgnoredWorkloadList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VhapeIgnoredWorkloadSpec) DeepCopyInto(out *VhapeIgnoredWorkloadSpec) {
	*out = *in
	out.TargetRef = in.TargetRef
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VhapeIgnoredWorkloadSpec.
func (in *VhapeIgnoredWorkloadSpec) DeepCopy() *VhapeIgnoredWorkloadSpec {
	if in == nil {
		return nil
	}
	out := new(VhapeIgnoredWorkloadSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VhapePolicy) DeepCopyInto(out *VhapePolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VhapePolicy.
func (in *VhapePolicy) DeepCopy() *VhapePolicy {
	if in == nil {
		return nil
	}
	out := new(VhapePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VhapePolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VhapePolicyList) DeepCopyInto(out *VhapePolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VhapePolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VhapePolicyList.
func (in *VhapePolicyList) DeepCopy() *VhapePolicyList {
	if in == nil {
		return nil
	}
	out := new(VhapePolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VhapePolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VhapePolicySpec) DeepCopyInto(out *VhapePolicySpec) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VhapePolicySpec.
func (in *VhapePolicySpec) DeepCopy() *VhapePolicySpec {
	if in == nil {
		return nil
	}
	out := new(VhapePolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VhapeResourcesSpec) DeepCopyInto(out *VhapeResourcesSpec) {
	*out = *in
	if in.CPU != nil {
		in, out := &in.CPU, &out.CPU
		*out = make(ResourceHeuristics, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Memory != nil {
		in, out := &in.Memory, &out.Memory
		*out = make(ResourceHeuristics, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VhapeResourcesSpec.
func (in *VhapeResourcesSpec) DeepCopy() *VhapeResourcesSpec {
	if in == nil {
		return nil
	}
	out := new(VhapeResourcesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VhapeWatchedNamespace) DeepCopyInto(out *VhapeWatchedNamespace) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VhapeWatchedNamespace.
func (in *VhapeWatchedNamespace) DeepCopy() *VhapeWatchedNamespace {
	if in == nil {
		return nil
	}
	out := new(VhapeWatchedNamespace)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VhapeWatchedNamespace) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VhapeWatchedNamespaceList) DeepCopyInto(out *VhapeWatchedNamespaceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VhapeWatchedNamespace, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VhapeWatchedNamespaceList.
func (in *VhapeWatchedNamespaceList) DeepCopy() *VhapeWatchedNamespaceList {
	if in == nil {
		return nil
	}
	out := new(VhapeWatchedNamespaceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VhapeWatchedNamespaceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VhapeWatchedNamespaceRegex) DeepCopyInto(out *VhapeWatchedNamespaceRegex) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VhapeWatchedNamespaceRegex.
func (in *VhapeWatchedNamespaceRegex) DeepCopy() *VhapeWatchedNamespaceRegex {
	if in == nil {
		return nil
	}
	out := new(VhapeWatchedNamespaceRegex)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VhapeWatchedNamespaceRegex) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VhapeWatchedNamespaceRegexList) DeepCopyInto(out *VhapeWatchedNamespaceRegexList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VhapeWatchedNamespaceRegex, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VhapeWatchedNamespaceRegexList.
func (in *VhapeWatchedNamespaceRegexList) DeepCopy() *VhapeWatchedNamespaceRegexList {
	if in == nil {
		return nil
	}
	out := new(VhapeWatchedNamespaceRegexList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VhapeWatchedNamespaceRegexList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VhapeWatchedNamespaceRegexSpec) DeepCopyInto(out *VhapeWatchedNamespaceRegexSpec) {
	*out = *in
	out.VhapeWatchedNamespaceSpec = in.VhapeWatchedNamespaceSpec
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VhapeWatchedNamespaceRegexSpec.
func (in *VhapeWatchedNamespaceRegexSpec) DeepCopy() *VhapeWatchedNamespaceRegexSpec {
	if in == nil {
		return nil
	}
	out := new(VhapeWatchedNamespaceRegexSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VhapeWatchedNamespaceSpec) DeepCopyInto(out *VhapeWatchedNamespaceSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VhapeWatchedNamespaceSpec.
func (in *VhapeWatchedNamespaceSpec) DeepCopy() *VhapeWatchedNamespaceSpec {
	if in == nil {
		return nil
	}
	out := new(VhapeWatchedNamespaceSpec)
	in.DeepCopyInto(out)
	return out
}
