/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	autoscalingvhapeiov1alpha1 "k8s.io/autoscaler/vertical-pod-autoscaler/pkg/apis/autoscaling.vhape.io/v1alpha1"
	scheme "k8s.io/autoscaler/vertical-pod-autoscaler/pkg/client/clientset/versioned/scheme"
	gentype "k8s.io/client-go/gentype"
)

// VhapePoliciesGetter has a method to return a VhapePolicyInterface.
// A group's client should implement this interface.
type VhapePoliciesGetter interface {
	VhapePolicies() VhapePolicyInterface
}

// VhapePolicyInterface has methods to work with VhapePolicy resources.
type VhapePolicyInterface interface {
	Create(ctx context.Context, vhapePolicy *autoscalingvhapeiov1alpha1.VhapePolicy, opts v1.CreateOptions) (*autoscalingvhapeiov1alpha1.VhapePolicy, error)
	Update(ctx context.Context, vhapePolicy *autoscalingvhapeiov1alpha1.VhapePolicy, opts v1.UpdateOptions) (*autoscalingvhapeiov1alpha1.VhapePolicy, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*autoscalingvhapeiov1alpha1.VhapePolicy, error)
	List(ctx context.Context, opts v1.ListOptions) (*autoscalingvhapeiov1alpha1.VhapePolicyList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *autoscalingvhapeiov1alpha1.VhapePolicy, err error)
	VhapePolicyExpansion
}

// vhapePolicies implements VhapePolicyInterface
type vhapePolicies struct {
	*gentype.ClientWithList[*autoscalingvhapeiov1alpha1.VhapePolicy, *autoscalingvhapeiov1alpha1.VhapePolicyList]
}

// newVhapePolicies returns a VhapePolicies
func newVhapePolicies(c *VhapeAutoscalingV1alpha1Client) *vhapePolicies {
	return &vhapePolicies{
		gentype.NewClientWithList[*autoscalingvhapeiov1alpha1.VhapePolicy, *autoscalingvhapeiov1alpha1.VhapePolicyList](
			"vhapepolicies",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *autoscalingvhapeiov1alpha1.VhapePolicy { return &autoscalingvhapeiov1alpha1.VhapePolicy{} },
			func() *autoscalingvhapeiov1alpha1.VhapePolicyList {
				return &autoscalingvhapeiov1alpha1.VhapePolicyList{}
			},
		),
	}
}
