/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	autoscalingvhapeiov1alpha1 "k8s.io/autoscaler/vertical-pod-autoscaler/pkg/apis/autoscaling.vhape.io/v1alpha1"
	scheme "k8s.io/autoscaler/vertical-pod-autoscaler/pkg/client/clientset/versioned/scheme"
	gentype "k8s.io/client-go/gentype"
)

// VhapeWatchedNamespacesGetter has a method to return a VhapeWatchedNamespaceInterface.
// A group's client should implement this interface.
type VhapeWatchedNamespacesGetter interface {
	VhapeWatchedNamespaces() VhapeWatchedNamespaceInterface
}

// VhapeWatchedNamespaceInterface has methods to work with VhapeWatchedNamespace resources.
type VhapeWatchedNamespaceInterface interface {
	Create(ctx context.Context, vhapeWatchedNamespace *autoscalingvhapeiov1alpha1.VhapeWatchedNamespace, opts v1.CreateOptions) (*autoscalingvhapeiov1alpha1.VhapeWatchedNamespace, error)
	Update(ctx context.Context, vhapeWatchedNamespace *autoscalingvhapeiov1alpha1.VhapeWatchedNamespace, opts v1.UpdateOptions) (*autoscalingvhapeiov1alpha1.VhapeWatchedNamespace, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*autoscalingvhapeiov1alpha1.VhapeWatchedNamespace, error)
	List(ctx context.Context, opts v1.ListOptions) (*autoscalingvhapeiov1alpha1.VhapeWatchedNamespaceList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *autoscalingvhapeiov1alpha1.VhapeWatchedNamespace, err error)
	VhapeWatchedNamespaceExpansion
}

// vhapeWatchedNamespaces implements VhapeWatchedNamespaceInterface
type vhapeWatchedNamespaces struct {
	*gentype.ClientWithList[*autoscalingvhapeiov1alpha1.VhapeWatchedNamespace, *autoscalingvhapeiov1alpha1.VhapeWatchedNamespaceList]
}

// newVhapeWatchedNamespaces returns a VhapeWatchedNamespaces
func newVhapeWatchedNamespaces(c *VhapeAutoscalingV1alpha1Client) *vhapeWatchedNamespaces {
	return &vhapeWatchedNamespaces{
		gentype.NewClientWithList[*autoscalingvhapeiov1alpha1.VhapeWatchedNamespace, *autoscalingvhapeiov1alpha1.VhapeWatchedNamespaceList](
			"vhapewatchednamespaces",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *autoscalingvhapeiov1alpha1.VhapeWatchedNamespace {
				return &autoscalingvhapeiov1alpha1.VhapeWatchedNamespace{}
			},
			func() *autoscalingvhapeiov1alpha1.VhapeWatchedNamespaceList {
				return &autoscalingvhapeiov1alpha1.VhapeWatchedNamespaceList{}
			},
		),
	}
}
