/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	labels "k8s.io/apimachinery/pkg/labels"
	autoscalingvhapeiov1alpha1 "k8s.io/autoscaler/vertical-pod-autoscaler/pkg/apis/autoscaling.vhape.io/v1alpha1"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// VhapeIgnoredNamespaceLister helps list VhapeIgnoredNamespaces.
// All objects returned here must be treated as read-only.
type VhapeIgnoredNamespaceLister interface {
	// List lists all VhapeIgnoredNamespaces in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*autoscalingvhapeiov1alpha1.VhapeIgnoredNamespace, err error)
	// Get retrieves the VhapeIgnoredNamespace from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*autoscalingvhapeiov1alpha1.VhapeIgnoredNamespace, error)
	VhapeIgnoredNamespaceListerExpansion
}

// vhapeIgnoredNamespaceLister implements the VhapeIgnoredNamespaceLister interface.
type vhapeIgnoredNamespaceLister struct {
	listers.ResourceIndexer[*autoscalingvhapeiov1alpha1.VhapeIgnoredNamespace]
}

// NewVhapeIgnoredNamespaceLister returns a new VhapeIgnoredNamespaceLister.
func NewVhapeIgnoredNamespaceLister(indexer cache.Indexer) VhapeIgnoredNamespaceLister {
	return &vhapeIgnoredNamespaceLister{listers.New[*autoscalingvhapeiov1alpha1.VhapeIgnoredNamespace](indexer, autoscalingvhapeiov1alpha1.Resource("vhapeignorednamespace"))}
}
