apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: vpa-vanilla
  namespace: default
  annotations:
    vhape/policy: "default"
spec:
  recommenders:
    - name: custom-recommender
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: my-app
  updatePolicy:
    updateMode: "Recreate"
  resourcePolicy:
    containerPolicies:
      - containerName: "*"
        controlledValues: RequestsOnly