apiVersion: autoscaling.vhape.io/v1alpha1
kind: VhapePolicy
metadata:
  name: vhape-policy-p93-default
  namespace: kube-system
spec:
  resources:
    cpu:
      percentile-hysteresis:
        percentile: 0.93
        headroom: 0.10
        slidingWindow: 24h
    memory:
      percentile-hysteresis:
        percentile: 0.93
        headroom: 0.05
        slidingWindow: 24h
  scalingRule: ""