/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	apisautoscalingvhapeiov1alpha1 "k8s.io/autoscaler/vertical-pod-autoscaler/pkg/apis/autoscaling.vhape.io/v1alpha1"
	versioned "k8s.io/autoscaler/vertical-pod-autoscaler/pkg/client/clientset/versioned"
	internalinterfaces "k8s.io/autoscaler/vertical-pod-autoscaler/pkg/client/informers/externalversions/internalinterfaces"
	autoscalingvhapeiov1alpha1 "k8s.io/autoscaler/vertical-pod-autoscaler/pkg/client/listers/autoscaling.vhape.io/v1alpha1"
	cache "k8s.io/client-go/tools/cache"
)

// VhapeIgnoredWorkloadInformer provides access to a shared informer and lister for
// VhapeIgnoredWorkloads.
type VhapeIgnoredWorkloadInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() autoscalingvhapeiov1alpha1.VhapeIgnoredWorkloadLister
}

type vhapeIgnoredWorkloadInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewVhapeIgnoredWorkloadInformer constructs a new informer for VhapeIgnoredWorkload type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewVhapeIgnoredWorkloadInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredVhapeIgnoredWorkloadInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredVhapeIgnoredWorkloadInformer constructs a new informer for VhapeIgnoredWorkload type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredVhapeIgnoredWorkloadInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.VhapeAutoscalingV1alpha1().VhapeIgnoredWorkloads().List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.VhapeAutoscalingV1alpha1().VhapeIgnoredWorkloads().Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.VhapeAutoscalingV1alpha1().VhapeIgnoredWorkloads().List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.VhapeAutoscalingV1alpha1().VhapeIgnoredWorkloads().Watch(ctx, options)
			},
		}, client),
		&apisautoscalingvhapeiov1alpha1.VhapeIgnoredWorkload{},
		resyncPeriod,
		indexers,
	)
}

func (f *vhapeIgnoredWorkloadInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredVhapeIgnoredWorkloadInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *vhapeIgnoredWorkloadInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apisautoscalingvhapeiov1alpha1.VhapeIgnoredWorkload{}, f.defaultInformer)
}

func (f *vhapeIgnoredWorkloadInformer) Lister() autoscalingvhapeiov1alpha1.VhapeIgnoredWorkloadLister {
	return autoscalingvhapeiov1alpha1.NewVhapeIgnoredWorkloadLister(f.Informer().GetIndexer())
}
