/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	apisautoscalingvhapeiov1alpha1 "k8s.io/autoscaler/vertical-pod-autoscaler/pkg/apis/autoscaling.vhape.io/v1alpha1"
	versioned "k8s.io/autoscaler/vertical-pod-autoscaler/pkg/client/clientset/versioned"
	internalinterfaces "k8s.io/autoscaler/vertical-pod-autoscaler/pkg/client/informers/externalversions/internalinterfaces"
	autoscalingvhapeiov1alpha1 "k8s.io/autoscaler/vertical-pod-autoscaler/pkg/client/listers/autoscaling.vhape.io/v1alpha1"
	cache "k8s.io/client-go/tools/cache"
)

// VhapeWatchedNamespaceRegexInformer provides access to a shared informer and lister for
// VhapeWatchedNamespaceRegexes.
type VhapeWatchedNamespaceRegexInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() autoscalingvhapeiov1alpha1.VhapeWatchedNamespaceRegexLister
}

type vhapeWatchedNamespaceRegexInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewVhapeWatchedNamespaceRegexInformer constructs a new informer for VhapeWatchedNamespaceRegex type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewVhapeWatchedNamespaceRegexInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredVhapeWatchedNamespaceRegexInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredVhapeWatchedNamespaceRegexInformer constructs a new informer for VhapeWatchedNamespaceRegex type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredVhapeWatchedNamespaceRegexInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.VhapeAutoscalingV1alpha1().VhapeWatchedNamespaceRegexes().List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.VhapeAutoscalingV1alpha1().VhapeWatchedNamespaceRegexes().Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.VhapeAutoscalingV1alpha1().VhapeWatchedNamespaceRegexes().List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.VhapeAutoscalingV1alpha1().VhapeWatchedNamespaceRegexes().Watch(ctx, options)
			},
		}, client),
		&apisautoscalingvhapeiov1alpha1.VhapeWatchedNamespaceRegex{},
		resyncPeriod,
		indexers,
	)
}

func (f *vhapeWatchedNamespaceRegexInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredVhapeWatchedNamespaceRegexInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *vhapeWatchedNamespaceRegexInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apisautoscalingvhapeiov1alpha1.VhapeWatchedNamespaceRegex{}, f.defaultInformer)
}

func (f *vhapeWatchedNamespaceRegexInformer) Lister() autoscalingvhapeiov1alpha1.VhapeWatchedNamespaceRegexLister {
	return autoscalingvhapeiov1alpha1.NewVhapeWatchedNamespaceRegexLister(f.Informer().GetIndexer())
}
