image:
  repository: vtexlsd/vhape-watcher
  tag: ""
  pullPolicy: IfNotPresent

config:
  workers: 1
  vhapeRecommenderName: vhape-recommender
  defaultVhapePolicyNamespace: kube-system
  defaultVhapePolicyName: vhape-policy-p93-default
  defaultVPAUpdateMode: InPlaceOrRecreate