image:
  repository: vtexlsd/vhape-watcher
  tag: ""
  pullPolicy: IfNotPresent

config:
  workers: 1
  kubeApiQps: 10
  kubeApiBurst: 20

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 512Mi