apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: vhapewatchednamespaceregexes.autoscaling.vhape.io
spec:
  group: autoscaling.vhape.io
  scope: Cluster
  names:
    plural: vhapewatchednamespaceregexes
    singular: vhapewatchednamespaceregex
    kind: VhapeWatchedNamespaceRegex
    listKind: VhapeWatchedNamespaceRegexList
  versions:
    - name: v1alpha1
      served: true
      storage: true
      additionalPrinterColumns:
        - jsonPath: .spec.regex
          name: Regex
          type: string
        - jsonPath: .spec.vhapePolicyName
          name: PolicyName
          type: string
        - jsonPath: .spec.vpaUpdateMode
          name: UpdateMode
          type: string
      schema:
        openAPIV3Schema:
          type: object
          description: Marks namespaces matching a regular expression as eligible for VHAPE Watcher management.
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - regex
                - vhapePolicyName
                - vpaUpdateMode
              properties:
                regex:
                  type: string
                  minLength: 1
                vhapePolicyName:
                  type: string
                  minLength: 1
                vpaUpdateMode:
                  type: string
                  enum:
                    - Off
                    - Initial
                    - Recreate
                    - InPlaceOrRecreate
