apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: vhapewatchednamespaces.autoscaling.vhape.io
spec:
  group: autoscaling.vhape.io
  scope: Cluster
  names:
    plural: vhapewatchednamespaces
    singular: vhapewatchednamespace
    kind: VhapeWatchedNamespace
    listKind: VhapeWatchedNamespaceList
    shortNames:
      - vwn
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          description: Marks a Kubernetes namespace as eligible for VHAPE Watcher management.
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object